### ISSUE TITLE
fix error when call method initTable() too many

### ISSUE THREAD

**Issue by vinhdat4999** [canleit5509/ProjectManagement#12]

**Comment by canleit5509** [comment]
![image](https://user-images.githubusercontent.com/42709796/96618680-714a0880-132f-11eb-8abe-991a7823d3a2.png)

**Comment by vinhdat4999** [comment]
click nhiều lần đã fix lỗi như trên, nhưng thao tác với các button nhiều lần vẫn bị lỗi như trên chưa fix dc

**Comment by canleit5509** [comment]
`**Hàm initTable gọi eventHandler  sau đó eventHandler lại gọi initTable nên mới bị lỗi call method initTable() too many**

**Comment by canleit5509** [comment]
fixed
